language: rust
os: linux
cache: cargo

script: cargo test --all

before_deploy: cargo doc --all
deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: target/doc
  keep-history: false
  on:
    branch: master
skip_cleanup: true
