language: rust
os: linux
cache: cargo
addons:
  apt:
    packages:
    - libnotify-dev

script: make test doc

deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: target/doc
  keep-history: false
  on:
    branch: master
- provider: releases
  api_key: $GITHUB_TOKEN
  file: target/release/stahlnet-relay
  on:
    tags: true
  skip_cleanup: true
skip_cleanup: true
