language: rust
os: linux
cache: cargo
addons:
  apt:
    packages:
    - libnotify-dev

script: make test doc build-dist

deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: target/doc
  keep-history: false
  on:
    branch: master
- provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - target/dist/stahlnet-relay-lite
  - target/dist/stahlnet-relay-nogui
  - target/dist/stahlnet-relay
  on:
    tags: true
  skip_cleanup: true
skip_cleanup: true
