(function() {var implementors = {};
implementors["gdk_pixbuf"] = [{text:"impl <a class=\"trait\" href=\"glib/object/trait.IsA.html\" title=\"trait glib::object::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"glib/object/struct.Object.html\" title=\"struct glib::object::Object\">Object</a>&gt; for <a class=\"struct\" href=\"gdk_pixbuf/struct.PixbufAnimationIter.html\" title=\"struct gdk_pixbuf::PixbufAnimationIter\">PixbufAnimationIter</a>",synthetic:false,types:["gdk_pixbuf::animation::PixbufAnimationIter"]},{text:"impl <a class=\"trait\" href=\"glib/object/trait.IsA.html\" title=\"trait glib::object::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"glib/object/struct.Object.html\" title=\"struct glib::object::Object\">Object</a>&gt; for <a class=\"struct\" href=\"gdk_pixbuf/struct.PixbufAnimation.html\" title=\"struct gdk_pixbuf::PixbufAnimation\">PixbufAnimation</a>",synthetic:false,types:["gdk_pixbuf::animation::PixbufAnimation"]},{text:"impl <a class=\"trait\" href=\"glib/object/trait.IsA.html\" title=\"trait glib::object::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"gdk_pixbuf/struct.PixbufAnimation.html\" title=\"struct gdk_pixbuf::PixbufAnimation\">PixbufAnimation</a>&gt; for <a class=\"struct\" href=\"gdk_pixbuf/struct.PixbufSimpleAnim.html\" title=\"struct gdk_pixbuf::PixbufSimpleAnim\">PixbufSimpleAnim</a>",synthetic:false,types:["gdk_pixbuf::animation::PixbufSimpleAnim"]},{text:"impl <a class=\"trait\" href=\"glib/object/trait.IsA.html\" title=\"trait glib::object::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"glib/object/struct.Object.html\" title=\"struct glib::object::Object\">Object</a>&gt; for <a class=\"struct\" href=\"gdk_pixbuf/struct.PixbufSimpleAnim.html\" title=\"struct gdk_pixbuf::PixbufSimpleAnim\">PixbufSimpleAnim</a>",synthetic:false,types:["gdk_pixbuf::animation::PixbufSimpleAnim"]},{text:"impl <a class=\"trait\" href=\"glib/object/trait.IsA.html\" title=\"trait glib::object::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"glib/object/struct.Object.html\" title=\"struct glib::object::Object\">Object</a>&gt; for <a class=\"struct\" href=\"gdk_pixbuf/struct.PixbufLoader.html\" title=\"struct gdk_pixbuf::PixbufLoader\">PixbufLoader</a>",synthetic:false,types:["gdk_pixbuf::loader::PixbufLoader"]},{text:"impl <a class=\"trait\" href=\"glib/object/trait.IsA.html\" title=\"trait glib::object::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"glib/object/struct.Object.html\" title=\"struct glib::object::Object\">Object</a>&gt; for <a class=\"struct\" href=\"gdk_pixbuf/struct.Pixbuf.html\" title=\"struct gdk_pixbuf::Pixbuf\">Pixbuf</a>",synthetic:false,types:["gdk_pixbuf::pixbuf::Pixbuf"]},];
implementors["glib"] = [];
implementors["libnotify"] = [{text:"impl <a class=\"trait\" href=\"glib/object/trait.IsA.html\" title=\"trait glib::object::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"glib/object/struct.Object.html\" title=\"struct glib::object::Object\">Object</a>&gt; for <a class=\"struct\" href=\"libnotify/struct.Notification.html\" title=\"struct libnotify::Notification\">Notification</a>",synthetic:false,types:["libnotify::notification::Notification"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
